### PR TITLE
Fix problem

### PR DESCRIPTION
**Pull request by arnaud-m**
Next project to update: samples.

### CODE REVIEW

**Comment by cprudhom** [comment]
You added a generic parameter <T> but:
- you didn't javodoc it
- you didn't declare `getModel()` or equivalent method. 

I would add such a method, otherwise I don't see clearly what the interface is generic for.

**Comment by cprudhom** [comment]
My bad, I missed it.
Ok, so forget about my second question.

**Comment by arnaud-m** [comment]
`getModel` is below `buildModel`. 

I will add the javadoc for the generic parameter now.

**Comment by arnaud-m** [comment]
OK,  will you add the javadoc for the generic type and publish a new release of the facade ?

**Comment by arnaud-m** [comment]
OK, you are very fast ;)

**Comment by cprudhom** [comment]
samples is ready to be released too

**Comment by arnaud-m** [comment]
Wait, I update the project and check if my local changes are taken into account.

**Comment by arnaud-m** [comment]
Waiting for https://github.com/chocoteam/pf4cs/issues/3 in pf4cs

**Comment by arnaud-m** [comment]
I have nothing to modify in samples.

**Pull request merged**
